chat/urls.py
from django.urls import path
from chat import views

app_name = "chat"

urlpatterns = [
    path('rooms/', views.user_rooms, name="user_rooms"),
    path('creae/', views.create_room, name="create_room"),
    path('delete/<int:room_pk>/', views.delete_room, name="delete_room"),
    path("update/<int:room_pk>/", views.update_room, name="update_room"),
    path("leave/<int:room_pk>/", views.leave_room, name="leave_room"),
    path("members/<int:room_pk>/", views.room_members, name="room_members"),
    path('users/', views.all_users, name="all_users"),
]

dv_tool/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('delegates/', include('delegates.urls')),
    path('votes/', include('votes.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("speakers/", include("speakers.urls")),
    path("chat/", include("chat.urls")),
    path('', include('events.urls')),
]

events/urls.py
from events import views
from django.urls import path

app_name = "events"

urlpatterns = (
    path("", views.event_list, name="event_list"),
    path("<uuid:event_pk>/", views.event_detail, name="event_detail"),
    path("<uuid:event_pk>/info/", views.event_info, name="event_info"),
    path("<uuid:event_pk>/vote/", views.event_vote, name="event_vote"),
    path("<uuid:event_pk>/screen/", views.vote_screen, name="vote_screen"),
    path("<uuid:event_pk>/screen/info/", views.vote_screen_info, name="vote_screen_info"),
    path("<uuid:event_pk>/message/", views.chat_message, name="send_message"),
    path("<uuid:event_pk>/results/", views.event_vote_results, name="event_vote_results"),
    path("<uuid:event_pk>/admin/", views.event_admin, name="event_admin"),
    path("<uuid:event_pk>/operator/", views.operator_start, name="operator_start"),
    path("<uuid:event_pk>/operator/<int:operator>/",
         views.operator_view,
         name="operator_view"),
    path("<uuid:event_pk>/operator/<int:operator>/info/",
         views.operator_info,
         name="operator_info"),
    path("<uuid:event_pk>/admin/info/", views.event_admin_info, name="event_admin_info"),
)

speakers/urls.py
from speakers import views
from django.urls import path

app_name = "speakers"

urlpatterns = [
    path('create/', views.create_speak_request, name="create_request"),
    path('delete/<int:request_id>/', views.delete_request, name="delete_request"),
    path('action/', views.room_action, name="join_room"),
    path('send-mail/', views.send_speaker_mail, name="send_mail")
]

events/models.py
from csv import DictReader
import secrets
import uuid

from django.contrib.auth import get_user_model
from delegates.models import INVITE_CREATED, INVITE_PROCESSED, INVITE_SENT, Invite
from django.core.mail import send_mail, send_mass_mail
from django.contrib.auth.models import Group
from django.db import models
from django.utils.translation import gettext as _

from django.core.files.storage import FileSystemStorage
from django.conf import settings

upload_storage = FileSystemStorage(location=settings.UPLOAD_ROOT, base_url='/uploads')

# Create your models here.


class Event(models.Model):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)

    title = models.CharField(max_length=255, verbose_name=_("Titel"))
    date = models.DateField(verbose_name=_("Datum"))

    invite_mail_sender = models.CharField(max_length=255, verbose_name=_("Einlaundgsmail Absender*in"))
    invite_mail_subject = models.CharField(max_length=255, verbose_name=_("Einlaundgsmail Betreff"))
    invite_mail_template = models.TextField(verbose_name=_("Einlaundgsmail Vorlage"), help_text=_("Text, den die Delegierten erhalten, Platzhalter für den Code: {code}, für die id des Events: {id}"))

    reminder_mail_subject = models.CharField(max_length=255, verbose_name=_("Erinnerungsmail Betreff"), blank=True)
    reminder_mail_template = models.TextField(verbose_name=_("Erinnerungsmail Vorlage"), help_text=_("Text, den die Delegierten erhalten, Platzhalter für den Code: {code}, für die id des Events: {id}"), blank=True)

    is_open = models.BooleanField(default=False, verbose_name=_("ist offen"))
    is_simple = models.BooleanField(default=False, verbose_name=_("Simpel"))
    need_summary = models.BooleanField(default=False)
    need_reason = models.BooleanField(default=False)
    need_gender = models.BooleanField(default=False)

    mail_file = models.FileField(verbose_name=_("E-Mail Datei"), storage=upload_storage)

    embed_code = models.TextField(blank=True)

    mail_config = models.ForeignKey(
        "speakers.MailConfiguration",
        models.SET_NULL,
        null=True,
        blank=True,
    )

    managers = models.ManyToManyField(get_user_model())
    operators = models.ManyToManyField(get_user_model(), related_name="+")

    def process_invites(self):
        self.reset_invites()
        with self.mail_file.open('r') as f:
            reader = DictReader(f)
            for row in reader:
                group, _ = Group.objects.get_or_create(name=row.get('group'))
                Invite.objects.create(
                    event=self,
                    user=None,
                    primary_mail=row.get('email'),
                    first_name=row.get('first_name', ''),
                    last_name=row.get('last_name', ''),
                    section=group,
                    can_vote=bool(int(row.get('can_vote', '1'))),
                )

    def send_invites(self):
        messages = []

        for invite in self.invite_set.filter(state=INVITE_CREATED):
            messages.append((self.invite_mail_subject,
                             self.invite_mail_template.format(code=invite.code,
                                                              id=self.pk,
                                                              email=invite.primary_mail),
                             self.invite_mail_sender, [invite.primary_mail]))
        self.invite_set.all().update(state=INVITE_SENT)
        send_mass_mail(messages)

    def send_invites_with_pw(self):
        messages = []

        for invite in self.invite_set.filter(state=INVITE_CREATED):
            user, _ = get_user_model().objects.get_or_create(
                username=invite.primary_mail,
                defaults={
                    'email': invite.primary_mail,
                    'username': invite.primary_mail,
                    'first_name': invite.first_name,
                    'last_name': invite.last_name,
                },
            )
            password = secrets.token_urlsafe(12)
            user.set_password(password)
            user.save()
            invite.user = user
            invite.save()
            messages.append((self.invite_mail_subject,
                             self.invite_mail_template.format(
                                 email=user.email,
                                 password=password,
                                 id=invite.event.pk,
                             ), self.invite_mail_sender, [invite.primary_mail]))

        self.invite_set.all().update(state=INVITE_PROCESSED)
        send_mass_mail(messages)

    def send_reminder(self):
        messages = []

        for invite in self.invite_set.filter(state=INVITE_SENT):
            messages.append(
                (self.reminder_mail_subject,
                 self.reminder_mail_template.format(code=invite.code,
                                                    id=self.pk,
                                                    email=invite.primary_mail),
                 self.invite_mail_sender, [invite.primary_mail]))
        send_mass_mail(messages)

    def reset_invites(self):
        self.invite_set.filter(state=INVITE_CREATED).delete()

    def __str__(self):
        return self.title + ", " + self.date.strftime("%Y-%m-%d")

    class Meta:
        verbose_name = _("Anlass")
        verbose_name_plural = _("Anlässe")


class VideoLink(models.Model):
    name = models.CharField(max_length=255, verbose_name=_("Name"))
    embed_code = models.TextField(verbose_name=_("Einbettungscode"))
    event = models.ForeignKey(Event, models.CASCADE, verbose_name=_("Event"))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Video Link")
        verbose_name_plural = _("Video Links")


class ChatWindow(models.Model):
    name = models.CharField(max_length=255, verbose_name=_("chat window"))
    event = models.ForeignKey(Event, models.CASCADE, verbose_name=_("Event"))

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = _("Chat Window")
        verbose_name_plural = _("Chat Windows")

events/forms.py
from django import forms
from django.forms import widgets
from multiupload.fields import MultiFileField


class MessageForm(forms.Form):
    subject = forms.CharField()

    content = forms.CharField(widget=widgets.Textarea)

    attachments = MultiFileField(min_num=0, max_num=5)


class OperatorForm(forms.Form):
    operator_nr = forms.IntegerField()

events/templates/events/event_admin.html
{% extends 'base.html' %}

{% load static bootstrap5 i18n %}

{% block title %}Admin - {{event.title}}{% endblock %}

{% block content %}
<div  id="app">
  <div class="row">
    <div class="col">
      <h2>{% trans 'Wortmeldungen' %}</h2>
      <table class="table table-sm">
        <thead>
          <tr>
            <th>
              {% trans 'Traktandum' %}
            </th>
            <th>
              {% trans 'Sprecher*in' %}
            </th>
            <th>
              {% trans 'Status' %}
            </th>
            <th>
              {% trans 'Wortmeldung' %}
            </th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="request in info.speakerRequests" v-bind:class="{
                       scheduled: request.state == {{SCHEDULED}},
                       waiting: request.state == {{WAITING}},
                       ready: request.state == {{READY}},
                       speaking: request.state == {{SPEAKING}},
                       done: request.state == {{DONE}},
                       }">
            <td>
              [[request.title]]
            </td>
            <td>
              [[request.name]]
            </td>
            <td>
              [[request.state_display]]
            </td>
            <td>
              [[request.reason]]
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="col">
      <h2>{% trans 'Abstimmungen' %}</h2>
      <div class="vote-info">

        <h2>[[info.vote_title]]</h2>

        <div class="vote-results"  v-if="info.vote_title">
          <span class="yes">
            <span v-if="info.text_yes">[[info.text_yes]]</span> 
            <span v-else>{% trans 'Ja' %}</span>: [[info.vote_yes]]</span>
          <span class="yes">
            <span v-if="info.text_no">[[info.text_no]]</span> 
            <span v-else>{% trans 'Nein' %}</span>: [[info.vote_no]]</span>
          <span class="yes">
            <span v-if="info.text_abstain">[[info.text_abstain]]</span> 
            <span v-else>{% trans 'Enthaltung' %}</span>: [[info.vote_abstain]]</span>
        </div>
        <div class="votes" id="votes">
        </div>
      </div>
      <table class="table table-sm">
        <thead>
          <tr>
            <th>{% trans 'Abstimmung' %}</th>
            <th>{% trans 'Ja' %}</th>
            <th>{% trans 'Nein' %}</th>
            <th>{% trans 'Enthaltung' %}</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="ballot in info.ballots">
            <td>[[ballot.title]]</td>
            <td><span v-if="ballot.text_yes" class="alt">[[ballot.text_yes]]:</span> [[ballot.yes]]</td>
            <td><span v-if="ballot.text_no" class="alt">[[ballot.text_no]]:</span> [[ballot.no]]</td>
            <td><span v-if="ballot.text_abstain" class="alt">[[ballot.text_abstain]]:</span> [[ballot.abstain]]</td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
  <div class="row">
    {% for chat in event.chatwindow_set.all %}
    <div class="col">
      <h3>{{chat.name}}</h3>
      <div class="chat d-flex flex-column">
        <div class="messages admin">
          <div v-for="message of messages['{{chat.id}}']" class="card">
            <div class="card-header text-muted">
              <small>
                [[message.first_name]] [[message.last_name]] - [[formatDate(new Date(message.timestamp))]]
              </small>
            </div>
            <div class="card-body" v-html="message.message">
            </div>
          </div>
        </div>
      </div>
    </div>
    {% endfor %}
  </div>
</div>
{% endblock %}

{% block scripts %}
{% if debug %}
<script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
{% else %}
<script src="https://cdn.jsdelivr.net/npm/vue@2"></script>
{% endif %}
<script src="https://d3js.org/d3.v6.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="{% static 'js/event_admin.js' %}"></script>
{% endblock %}

events/templates/events/event_detail.html
{% extends 'base.html' %}

{% load static bootstrap5 i18n %}

{% block styles %}
<link
       rel="stylesheet"
       href="https://cdn.jsdelivr.net/npm/choices.js/public/assets/styles/choices.min.css"
       />
{% endblock %}

{% block title %}{{event.title}} - {{event.date | date}}{% endblock %}

{% block content %}
<div class="row">
</div>
<div class="row" id="app">
  <span class="d-none" id="nameInput" data-value="{{request.user.get_full_name}}"></span>
  <span class="d-none" id="waitingCallMessage" data-value="{% trans 'Deine Wortmeldung kommt bald dran, klicke auf den blauen Link mit dem gelben Hintergrund um den Call zu starten!' %}"></span>
  <span class="d-none" id="redactConfirm" data-value="{% trans 'Bist du sicher?' %}"></span>
  <span class="d-none" id="hangupMessage" data-value="{% trans 'Beende den aktuellen Call, bevor du einen neuen anfängst.' %}"></span>
  <div class="col-lg-6 col-xl-7 col-xxl-8">
    <ul class="nav nav-tabs" id="videoTab" role="tablist">
      {% for video in event.videolink_set.all %}
      <li class="nav-item" role="presentation">
        <a class="nav-link {% if forloop.first %}active{% endif %}" id="video-tab-{{video.id}}" data-bs-toggle="tab" href="#video-{{video.id}}" role="tab" aria-controls="video-{{video.id}}" aria-selected="{% if forloop.first %}true{% else %}false{% endif %}">{{video.name}}</a>
      </li>
      {% endfor %}
    </ul>
    <div class="tab-content" id="videoTabContent">
      {% for video in event.videolink_set.all %}
      <div
          class="tab-pane fade {% if forloop.first %}show active{% endif %}"
          id="video-{{video.id}}"
          role="tabpanel"
          aria-labelledby="video-tab-{{video.id}}"
          >
          <div class="ratio ratio-16x9">
            {{video.embed_code|safe}}
          </div>
      </div>
      {% endfor %}

    </div>
    {% if request.user.is_authenticated %}
    <div class="row">
      <div class="col-md-6">
        {% if event.chatwindow_set.count %}
        <h3>{% trans "Chat" %}</h3>
        {% endif %}
        <ul class="nav nav-tabs" id="chatTab" role="tablist">
          {% for chat in event.chatwindow_set.all %}
          <li class="nav-item" role="presentation">
            <a class="nav-link {% if forloop.first %}active{% endif %}" id="chat-tab-{{chat.id}}" data-bs-toggle="tab" href="#chat-{{chat.id}}" role="tab" aria-controls="chat-{{chat.id}}" aria-selected="{% if forloop.first %}true{% else %}false{% endif %}">{{chat.name}}</a>
          </li>
          {% endfor %}
        </ul>
        <div class="tab-content" id="chatTabContent">
          {% for chat in event.chatwindow_set.all %}
          <div
              class="tab-pane fade {% if forloop.first %}show active{% endif %}"
              id="chat-{{chat.id}}"
              role="tabpanel"
              aria-labelledby="chat-tab-{{chat.id}}"
              >
              <div class="chat d-flex flex-column">
                <div class="messages">
                  <div v-for="message of messages['{{chat.id}}']" class="card" v-bind:class="{'me': message.user_id == {{request.user.pk}}}" >
                    <div class="card-header text-muted">
                      <small>
                        [[message.first_name]] [[message.last_name]] - [[formatDate(new Date(message.timestamp))]]
                      </small>
                    </div>
            <div class="card-body" v-html="message.message">
            </div>
                  </div>
                </div>
                <form data-channel="{{chat.id}}"
                      v-on:submit.prevent="sendMessage"
                      > 
                      <div class="input-group chat-input">
                        <input
                            id="input-{{chat.id}}"
                            type="text"
                            class="form-control"
                            autocomplete="off"
                            maxlength="280"
                            >
                            <button class="btn btn-outline-secondary" type="submit" >
                              {% trans 'Senden' %}
                            </button>
                      </div>
                </form>

              </div>
          </div>
          {% endfor %}
        </div>
      </div>

      <div class="vote-info col-md-6">
        <h2 class="h2">{% trans 'Abstimmungen' %}</h2>
        <h2 class="text-center"  v-if="info.vote_title">[[info.vote_title]]</h2>

        <div class="vote-results"  v-if="info.vote_title">
          <span class="yes">
            <span v-if="info.text_yes">[[info.text_yes]]</span> 
            <span v-else>{% trans 'Ja' %}</span>: [[info.vote_yes]]</span>
          <span class="yes">
            <span v-if="info.text_no">[[info.text_no]]</span> 
            <span v-else>{% trans 'Nein' %}</span>: [[info.vote_no]]</span>
          <span class="yes">
            <span v-if="info.text_abstain">[[info.text_abstain]]</span> 
            <span v-else>{% trans 'Enthaltung' %}</span>: [[info.vote_abstain]]</span>
        </div>

        <div class="votes" id="votes"  v-if="info.vote_title">
        </div>

        {% if can_vote %}
        <div class="vote-panel" id="vote-panel"  v-if="info.vote_title && info.can_vote">
          <div class="btn-group disabled" role="group">
            <button type="button" class="btn btn-outline-primary" @click="voteAction" data-value="1" v-bind:class="{active: info.user_vote == 1}">
              <template v-if="info.text_yes">[[info.text_yes]]</template> 
              <template v-else>{% trans 'Ja' %}</template>
            </button>
            <button type="button" class="btn btn-outline-danger" @click="voteAction" data-value="2" v-bind:class="{active: info.user_vote == 2}">
              <template v-if="info.text_no">[[info.text_no]]</template> 
              <template v-else>{% trans 'Nein' %}</template>
            </button>
            <button type="button" class="btn btn-outline-secondary" @click="voteAction" data-value="0" v-bind:class="{active: info.user_vote == 0}">
              <template v-if="info.text_abstain">[[info.text_abstain]]</template> 
              <template v-else>{% trans 'Enthaltung' %}</template>
            </button>
            <button type="button" class="btn btn-outline-dark" @click="voteAction" data-value="-1" v-bind:class="{active: info.user_vote == -1}">
              {% trans 'Keine' %}
            </button>
          </div>
        </div>
        {% endif %}
        <table class="table table-sm" v-if="info.ballots && info.ballots.length > 0">
          <thead>
            <tr>
              <th>{% trans 'Abstimmung' %}</th>
              <th>{% trans 'Ja' %}</th>
              <th>{% trans 'Nein' %}</th>
              <th>{% trans 'Enthaltung' %}</th>
            </tr>
          </thead>
          <tbody>
            <tr v-for="ballot in info.ballots">
              <td>[[ballot.title]]</td>
              <td>[[ballot.yes]]</td>
              <td>[[ballot.no]]</td>
              <td>[[ballot.abstain]]</td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
    {% endif %}
  </div>
  <div class="col-lg-6 col-xl-5 col-xxl-4">
    {% if request.user.is_authenticated %}
    <div class="speaker-info">

      {% if not request.user.is_authenticated %}
      <div class="alert alert-warning" role="alert">
        {% url 'login' as login_url %}
        {% blocktrans %}Du siehst du Versammlung als Gäst*in, um abzustimmen musst du dich <a href="{{login_url}}">hier</a> anmelden.{% endblocktrans %}
      </div>
      {% endif %}
      <h2>{% trans 'Deine Wortmeldungen' %}</h2>
      <table class="table" id="speakerRequests">
        <thead>
          <tr>
            <th>
              {% trans 'Traktandum' %}
            </th>
            <th colspan="2">
              {% trans 'Status' %}
            </th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="request in info.speakerRequests" v-bind:class="{
          scheduled: request.state == {{SCHEDULED}},
          waiting: request.state == {{WAITING}},
          ready: request.state == {{READY}},
          speaking: request.state == {{SPEAKING}},
          done: request.state == {{DONE}},
          }">
            <td>
              <a @click="joinMeeting" :data-id="request.id" :data-link="request.link" :href="'https://{{JITSI_DOMAIN}}/' + request.link" :title="request.title">
                [[truncate(request.title, 70)]]
              </a>
            </td>
            <td :data-state="request.state">
              [[request.state_display]]
            </td>
            <td>
              <a class="btn btn-primary btn-sm" @click="joinMeeting" :data-id="request.id" :data-link="request.link" :href="'https://{{JITSI_DOMAIN}}/' + request.link" :title="request.title">
                {% trans 'Beitreten' %}
              </a>
              <button
                :data-id="request.id"
                data-link="/speakers/delete/"
                type="button"
                class="btn btn-sm btn-danger"
                @click="deleteAction">
                {% trans 'Zurückziehen' %}
              </button>
            </td>
          </tr>
          <tr v-if="info.speakerRequests && info.speakerRequests.length <= 0">
            <td colspan="2">
              {% trans 'Noch keine Wortmeldungen' %}
            </td>
          </tr>
        </tbody>
      </table>
    </div>
    <h3>{% trans 'Wortmeldung einreichen' %}</h3>
    <form
      class="form"
      id="speakerForm"
      method="post"
      action="{% url 'speakers:create_request' %}"
      v-on:submit.prevent="submitForm"
      >
      {% bootstrap_form speaker_form %}
      {% buttons %}
      <button type="submit" class="btn btn-primary">{% trans 'Absenden' %}</button>
      {% endbuttons %}
    </form>

    <div class="ratio ratio-16x9">
      <div id="meet">
      </div>
    </div>
    {% else %}
    <div class="vote-info" v-if="info.vote_title">
      <h2 class="text-center">[[info.vote_title]]</h2>
      <div class="votes" id="votes">
      </div>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

{% block scripts %}
<script src="{% static 'js/smile2emoji.js' %}"></script>
{% if debug %}
<script src="https://cdn.jsdelivr.net/npm/vue@2/dist/vue.js"></script>
{% else %}
<script src="https://cdn.jsdelivr.net/npm/vue@2"></script>
{% endif %}
<script src="https://d3js.org/d3.v6.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/axios/dist/axios.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/choices.js/public/assets/scripts/choices.min.js"></script>
<script src="https://cdn.jsdelivr.net/npm/lodash@4.17.20/lodash.min.js" integrity="sha256-ur/YlHMU96MxHEsy3fHGszZHas7NzH4RQlD4tDVvFhw=" crossorigin="anonymous"></script>
<script src='https://{{JITSI_DOMAIN}}/external_api.js'></script>
<script src="https://www.youtube.com/iframe_api"></script>
<script src="{% static 'js/event_detail.js' %}"></script>
{% endblock %}

events/templates/events/event_list.html
{% extends 'base.html' %}
{% load i18n %}

{% block title %}{% trans 'Anlässe' %}{% endblock %}

{% block content %}
<div class="row">
  <div class="col-md-12">
    <h2>{% trans 'Anlässe' %}</h2>
    <table class="table">
      <thead>
        <tr>
          <th>{% trans 'Anlass' %}</th>
          <th>{% trans 'Datum' %}</th>
          {% if request.user.is_staff %}
          <th>{% trans 'Operator' %}</th>
          <th>{% trans 'Übersicht' %}</th>
          <th>{% trans 'Admin' %}</th>
          {% endif %}
        </tr>
      </thead>
      <tbody>
        {% for event in events %}
        <tr>
          <td>
            <a href="{% url 'events:event_detail' event.pk %}">{{event.title}}</a>
          </td>
          <td>
            {{event.date | date }}
          </td>
          {% if request.user.is_staff %}
          <td>
          {% if request.user in event.operators.all %}
            <a href="{% url 'events:operator_start' event.pk %}">
              {% trans 'Operator' %}
            </a>
          {% endif %}
          </td>
          <td>
          {% if request.user in event.managers.all %}
            <a href="{% url 'events:event_admin' event.pk %}">
              {% trans 'Overview' %}
            </a>
          {% endif %}
          </td>
          <td>
          {% if request.user in event.managers.all %}
            <a href="{% url 'admin:events_event_change' event.pk %}">
              {% trans 'Admin' %}
            </a>
          {% endif %}
          </td>
          {% endif %}
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>
</div>

{% endblock %}

events/templates/events/operator_start.html
{% extends 'base.html' %}
{% load i18n bootstrap5 %}

{% block title %}{{event.title}} - {{event.date | date}}{% endblock %}
{% block content %}


<div class="row">
  <div class="col-md-6 col-lg-5">
    <h2>{{event.title}}</h2>
    <form method="get" action="" class="form">
      {% bootstrap_form form %}
      {% buttons %}
      <button type="submit" class="btn btn-primary">{% trans 'Los' %}</button>
      {% endbuttons %}
    </form>
  </div>
</div>

{% endblock %}

events/templates/events/room_include.html
<div
      class="tab-pane fade"
      id="chat-rooms"
      role="tabpanel"
      aria-labelledby="chat-tab-rooms"
      >
      <table class="table table-sm">
        <thead>
          <tr>
            <th colspan="3">Raum</th>
          </tr>
        </thead>
        <tbody>
          <tr v-for="room of rooms.owned">
            <td>
              <a @click="joinMeeting" :data-link="room.link" :href="'https://{{JITSI_DOMAIN}}/' + room.link" :title="room.name">
                [[room.name]]
              </a>
            </td>
            <td>
              <button :data-id="room.id" data-link="/chat/delete/" type="button" class="btn btn-sm btn-danger" @click="deleteAction">
                {% trans 'Löschen' %}
              </button>
              <button :data-id="room.id" type="button" class="btn btn-sm btn-primary" @click="selectRoom">
                {% trans 'Mitglieder' %}
              </button>
            </td>
          </tr>
          <tr v-for="room of rooms.rooms">
            <td>
              <a @click="joinMeeting" :data-link="room.link" :href="'https://{{JITSI_DOMAIN}}/' + room.link" :title="room.name">
                [[room.name]]
              </a>
            </td>
            <td>
              <button :data-id="room.id" data-link="/chat/leave/" type="button" class="btn btn-sm btn-danger" @click="deleteAction">
                {% trans 'Verlassen' %}
              </button>
            </td>
          </tr>
        </tbody>
      </table>
      <form method="post" action="{% url 'chat:create_room' %}"
                          v-on:submit.prevent="submitForm">

        <div class="input-group chat-input">
          <input type="text" name="name" maxlength="120" required="required" id="id_name" class="form-control">
          <button type="submit" class="btn btn-primary btn-sm">{% trans 'Raum erstellen' %}</button>
        </div>
      </form>
      <div class="editMembers" v-bind:class="{'d-none': selectedRoom === undefined}">
        <div class="mt-2">{% trans 'Mitglieder' %}</div>
        <select id="userSelect"  multiple>
        </select>
        <div class="btn-group">
          <button type="button" class="btn btn-primary btn-sm" @click="updateMembers">
            {% trans 'Aktualisieren' %}
          </button>
          <button type="button" class="btn btn-danger btn-sm" @click="deselectRoom">
            {% trans 'Abbrechen' %}
          </button>
        </div>
      </div>
</div>