chat/urls.py
from django.urls import path
from chat import views

app_name = "chat"

urlpatterns = [
    path('rooms/', views.user_rooms, name="user_rooms"),
    path('creae/', views.create_room, name="create_room"),
    path('delete/<int:room_pk>/', views.delete_room, name="delete_room"),
    path("update/<int:room_pk>/", views.update_room, name="update_room"),
    path("leave/<int:room_pk>/", views.leave_room, name="leave_room"),
    path("members/<int:room_pk>/", views.room_members, name="room_members"),
    path('users/', views.all_users, name="all_users"),
]

dv_tool/urls.py
from django.contrib import admin
from django.urls import path
from django.urls.conf import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('delegates/', include('delegates.urls')),
    path('votes/', include('votes.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    path("speakers/", include("speakers.urls")),
    path("chat/", include("chat.urls")),
    path('', include('events.urls')),
]

events/urls.py
from events import views
from django.urls import path

app_name = "events"

urlpatterns = (
    path("", views.event_list, name="event_list"),
    path("<uuid:event_pk>/", views.event_detail, name="event_detail"),
    path("<uuid:event_pk>/info/", views.event_info, name="event_info"),
    path("<uuid:event_pk>/vote/", views.event_vote, name="event_vote"),
    path("<uuid:event_pk>/screen/", views.vote_screen, name="vote_screen"),
    path("<uuid:event_pk>/screen/info/", views.vote_screen_info, name="vote_screen_info"),
    path("<uuid:event_pk>/message/", views.chat_message, name="send_message"),
    path("<uuid:event_pk>/results/", views.event_vote_results, name="event_vote_results"),
    path("<uuid:event_pk>/admin/", views.event_admin, name="event_admin"),
    path("<uuid:event_pk>/operator/", views.operator_start, name="operator_start"),
    path("<uuid:event_pk>/operator/<int:operator>/",
         views.operator_view,
         name="operator_view"),
    path("<uuid:event_pk>/operator/<int:operator>/info/",
         views.operator_info,
         name="operator_info"),
    path("<uuid:event_pk>/admin/info/", views.event_admin_info, name="event_admin_info"),
)

templates/base.html
{% load static bootstrap5 %}
<!DOCTYPE html>
<html lang="{{request.LANGUAGE_CODE}}">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1"
      crossorigin="anonymous"
      />
    <link
      href="{% static 'css/variables.css' %}"
      rel="stylesheet"
      type="text/css"
      />

    {% block styles %}
    {% endblock %}

    <link href="{% static 'css/style.css' %}" rel="stylesheet" />

    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    {% block body %}
    <nav class="navbar">
      <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'events:event_list' %}">
          <img src="{{logo_url}}" alt="SP Logo" width="30">
        </a>
        <div class="navigation d-flex">
        {% if request.user.is_authenticated %}
        <a class="nav-link" aria-content="page" href="{% url 'logout' %}">Logout</a>
        {% endif %}
        {% if request.user.is_staff %}
        <a class="nav-link" aria-current="page" href="{% url 'admin:index' %}">Admin</a>
        {% endif %}
        </div>
      </div>
    </nav>
    {% if request.user.is_authenticated %}
    <span class="hidden" id="jitsiSettings" data-domain="{{JITSI_DOMAIN}}" data-prefix="{{JITSI_PREFIX}}"></span>
    {% endif %}
    {% bootstrap_messages %}
    <div class="container-fluid">{% block content %} {% endblock %}</div>
    {% endblock %}
    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW"
      crossorigin="anonymous"
      ></script>
    {% block scripts %}
    {% endblock %}
  </body>
</html>